#!/bin/sh

# Run OS File updates

# 20150724 update. Changes the Audio device ID for HDMI
chmod +x /usr/share/bootini/update_20150724.sh
/usr/share/bootini/update_20150724.sh


rm -fr /etc/initramfs-tools/scripts/local-top/display.sh

cp /media/boot/boot.ini /media/boot/boot.ini.old
cp /usr/share/bootini/boot.ini /media/boot/boot.ini

#copy the default settings file if it doesn't exist
if [ ! -f "/media/boot/boot.ini.default" ]; then
   cp /usr/share/bootini/boot.ini.default /media/boot/boot.ini.default
fi

#copy over user's custom settings (if any) from boot.ini.default
/usr/share/bootini/bootini-persistence.pl 2>&1 | tee /tmp/bootini-persistence.txt

/usr/sbin/update-initramfs -c -k `uname -r`
mkimage -A arm -O linux -T ramdisk -C none -a 0 -e 0 -n "uInitrd" -d /boot/initrd.img-`uname -r` /boot/uInitrd-`uname -r`
cp /boot/uInitrd-`uname -r` /media/boot/uInitrd

echo
echo
echo
echo
echo "A new boot.ini is installed." 
echo "Any changes to boot.ini is lost, such as display configuration" 
echo "Persistent custom settings from /media/boot/boot.ini.default have been restored"
echo "For reference your old boot.ini is saved to /media/boot/boot.ini.old"
